name: Event Driven Workflow Test

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Deployment Environment'
        required: true
        default: 'development'
        type: choice
        options:
          - staging
          - production

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code by tag
        uses: actions/checkout@v2
        with:
           fetch-depth: 0
      
      - run: |
          echo "Infra Environment : ${{ github.event.inputs.Environment }}"
          echo "Branch : ${{ github.ref }}"
