name: Event Driven Workflow Test

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Deployment Environment'
        required: true
        default: 'development'
        type: choice
        options:
          - staging
          - production

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:

      - run: |
          echo "Infra Environment : ${{ github.event.inputs.Environment }}"
          echo "Branch : ${{ github.ref }}"

      - name: Setup GitHub Code Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout Staging Code
        uses: actions/checkout@v2
        with: 
         ref : 'main'
        if: ${{ (inputs.Environment == 'staging') }}
      
      - name: Checkout Production Code
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $LATEST_TAG
          echo "Branch : ${{ github.ref }}"
        if: ${{ (inputs.Environment == 'production') }}
