name: Event Driven Workflow Test

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Deployment Environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  printInputs:
    runs-on: self-hosted
    steps:
      - run: |
          echo "Infra Environment : ${{ github.event.inputs.Environment }}"
          echo "Branch : ${{ github.ref }}"
